name: Knuddelparty-Plugin
version: 1.6
main: de.appstun.knuddelparty._Main
api-version: 1.17
authors: [Appstun]
description: Knuddel Spieler!

commands:
  knuddelparty:
    description: Starte eine Knuddelparty.
  join:
    description: Trete einer Knuddelparty bei.
  start:
    description: Starte eine Knuddelparty direkt.
  end:
    description: Beende eine Knuddelparty oder eine Einladung zu einer Knuddelparty.